{% set name = "badger-opt" %}
{% set version = "1.5.5" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 54b2acf524619669f60d4bc5d8381b7fa9a3a5bfb1bf3b958d00552cf6734b4a

build:
  number: 0
  noarch: python
  entry_points:
    - badger = badger.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - pyqt
    - pyqtgraph
    - qdarkstyle
    - coolname
    - pillow
    - requests
    - xopt >=3.0.0

test:
  imports:
    - badger
  commands:
    - badger --help
    - python -c "import badger; print(badger.__version__)"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xopt-org/Badger
  summary: Badger optimizer
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wenatuhs
    - pluflou
    - roussel-ryan
