{% set name = "badger-opt" %}
{% set version = "1.5.3" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 858a5254ef347f234ed3624e7b1b0d131550eb53309c31197e98d6821aa2c1b2

build:
  number: 0
  noarch: python
  entry_points:
    - badger = badger.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - pyqt
    - pyqtgraph
    - qdarkstyle
    - coolname
    - pillow
    - requests
    - xopt >=3.0.0

test:
  imports:
    - badger
  commands:
    - badger --help
    - python -c "import badger; print(badger.__version__)"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xopt-org/Badger
  summary: Badger optimizer
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wenatuhs
    - pluflou
    - roussel-ryan
